### ISSUE TITLE
Jasmine dependency ^2.0?

### ISSUE THREAD

**Issue by j-ulrich** [gburghardt/jasmine-data_driven_tests#2]
In the `bower.json`, you defined the Jasmine dependency to be `~2.0` which is equal to `>= 2.0.0 <2.1.0`
Shouldn't it be `^2.0`, i.e. `>=2.0.0 <3.0.0`?
Because it seems to run fine with `2.2.0`.

**Comment by gburghardt** [comment]
I'll see if I can get this updated soon. Thanks.

**Comment by gburghardt** [comment]
This should be fixed now with version 1.1.0 (Commit: ab62ee0b77eb8a60bfa9beb4e5e37df725c86978)

**Comment by gburghardt** [comment]
I'm closing this because it's been running fine on Jasmine 2.3 as well.
