### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by realityking** [gburghardt/jasmine-data_driven_tests#3]
Hi!

I just wanted to use this to clean up our tests, unfortunately it's not published to npm. Any chance of fixing this? Thank you!

**Comment by gburghardt** [comment]
I'm going to research this. I tried my hand at it and failed epically. I haven't written node modules before, so this will be a good learning experience. You could try your hand at it too. I accept pull requests for enhancements and bug fixes.

**Comment by cpcallen** [comment]
It looks like @dakolech has already done this: https://www.npmjs.com/package/jasmine-data_driven_tests
