### ISSUE TITLE
Error when using an array with more than one item on it

### ISSUE THREAD

**Issue by joaopgrassi** [gburghardt/jasmine-data_driven_tests#7]
I know it is noted on the "**When To Use Data Driven Tests**" section, but I think I have a good use case for using arrays as test data:

In our application we control what the user can do/see using claims. One similar use case is: 
We have a feature to rename an entity which has two implementations E.g _Rename BMW_ car and _Rename Ford car_. Both are implementations of _a Car_

We have 2 claims then: RenameBmwCar and RenameFordCar. Any user that has this claims can see the Rename Car button. Mainly, most of the Roles only have one Rename<brand>Car claim, but there's a role which is "Manager" that can rename both of them. E.g

Roles:
- BMWManager
   - RenameBmwCar
- FordManager
  - RenameFordCar
- Manager
  - RenameBmwCar
  - RenameFordCar

So, I wanted to write a test passing a combination of claims and assert that the button is shown. So, I tried this:

```
all('should show rename car button for roles',
[
  [Permission.BmwCar], // represents Bmw Manager
  [Permission.renameFordCar], // represents Ford Manager
  [Permission.BmwCar, Permission.renameFordCar] // represents Manager
],
(claims: any) => {

	// rest of test here
});
```

But this fails with:

_Jasmine.ArgumentCountMismatchError: Expecting data driven spec to accept 2 arguments, but 1 argument is specified in the callback function (should show rename car button for roles)
        at error (node_modules/jasmine-data_driven_tests/src/all.js:134:10)
        at createDataDrivenSpecs (node_modules/jasmine-data_driven_tests/src/all.js:100:10)_

If each array only has one item no error occurs:

```
all('should show rename car button for roles',
[
  [Permission.BmwCar],
  [Permission.renameFordCar],
  [Permission.BmwCar]
],
(claims: any) => {

	// rest of test here
});
```

**Comment by gburghardt** [comment]
This is intended behavior. I believe all you need to do nest arrays one more deep

```javascript
all('should show rename car button for roles',
[
  [
    [Permission.BmwCar]
  ], // represents Bmw Manager
  [
    [Permission.renameFordCar]
  ], // represents Ford Manager
  [
    [Permission.BmwCar, Permission.renameFordCar]
  ] // represents Manager
],
(claims: any) => {
	// rest of test here
});
```

**Comment by joaopgrassi** [comment]
I'm closing this.. since this is the intended behavior.
